version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
  backend:
    build: ./backend
    container_name: backend
    environment:
      - PORT=3000
    env_file:
      - ./backend/.env
    depends_on:
      - postgres